driver:
  name: vagrant
  provider: virtualbox
  gui: true

driver_config:
  guest: windows
  communicator: 'winrm'

provisioner:
  name: chef_zero

platforms:
  - name: windows2012r2

suites:
  - name: default
    run_list:
    - recipe[visualstudio::default]
    attributes:
      visualstudio:
        source: 'http://10.0.52.129:8080/'
        version: '2015'
        edition: 'enterprise'
        '2015':
          enterprise:
            # product_key: 'xxxx-xxxx-xxxx-xxxx-xxxx'
          professional:
            # product_key: 'xxxx-xxxx-xxxx-xxxx-xxxx'
        '2013':
          ultimate:
            # product_key: 'xxxx-xxxx-xxxx-xxxx-xxxx'
        preserve_extracted_files: true
